receivers:
  otlp:
    protocols:
      grpc: {}        # :4317
      http: {}        # :4318 (unused but handy)

processors:
  batch: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"   # Collector exposes /metrics here for Prometheus to scrape

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
